# Custom Language File for Launcher Customizer

[ejs.app]
title = "도트 런처"

[ejs.landing]
mediaGitHubURL = "https://github.com/K-SeongWon/DoteuLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/K-SeongWon/DoteuLauncher"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "환영합니다"
welcomeDescription = "도트 서버 접속을 위한 런처입니다."
welcomeDescCTA = "자세한 정보는 디스코드 채널을 참고해주세요."
